# Generated by Django 3.0.5 on 2020-12-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stocks',
            field=models.ManyToManyField(to='cart.Product'),
        ),
    ]
